name = "dianacf"
main = "src/index.js"
compatibility_date = "2024-04-01"

[[kv_namespaces]]
binding = "MINI_KV"
id = "MINI_KV" # Placeholder ID for local dev
preview_id = "ceac1b6d1fe449a9818b35c4c7277788"
